# Generated by Django 5.2.13 on 2026-04-18 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediciones', '0001_initial'),
        ('pronosticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrediccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo_calculado', models.CharField(max_length=20)),
                ('observacion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediciones.medicion')),
                ('pronostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronosticos.pronostico')),
            ],
        ),
    ]
