# Generated by Django 5.2.13 on 2026-04-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=20)),
                ('barrio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
