# Generated by Django 5.2.13 on 2026-04-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('probabilidad_lluvia', models.FloatField()),
                ('intensidad_lluvia', models.FloatField()),
                ('descripcion', models.CharField(max_length=100)),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
